# This is a basic workflow to help you get started with Actions
name: ExportAndBranchSolution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Enter Solution Name (internal name)'
        required: true
        default: 'TestSolution'
  
      source_environment:
        description: 'Source environment (Dynamics URL)'
        required: true
        default: 'https://orgee9eb49c.crm.dynamics.com/'

      target_environment:
        description: 'Target environment (Dynamics URL)'
        required: true
        default: 'https://orgab6ed293.crm5.dynamics.com/'
    
env:
  user_name: ChinnaSrihari@41c3jq.onmicrosoft.com
  secret: Sharcdot!300
  solution_export_folder: out/exported/${{github.event.inputs.solution_name}}
  solution_target_folder: solutions/${{github.event.inputs.solution_name}}
  
jobs:
  exprot-from-dev:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: set release date
        run: echo "release_date=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}
          fetch-depth: 0
      
      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i @v0
        with:
          environment-url: ${{github.event.inputs.source_environment}}
          user-name: ${{env.user_name}}
          password-secret: ${{env.secret}}


